import { QueryClient } from "@tanstack/react-query";
import "./globals.scss";
import type { Metadata } from "next";
import { Inter, Epilogue } from "next/font/google";
const inter = Epilogue({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
