import ThemeContextProvider from "@/patterns/context/ThemeContextProvider";
import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import "./globals.scss";
const inter = Epilogue({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeContextProvider>
      <html lang="en">
        <body className={`${inter.className} bg-white dark:bg-slate-950`}>
          {children}
        </body>
      </html>
    </ThemeContextProvider>
  );
}
